language: python
python:
- '3.5'
addons:
  ssh_known_hosts: 46.101.193.210
before_install:
- openssl aes-256-cbc -K $encrypted_f0aa0b639c80_key -iv $encrypted_f0aa0b639c80_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install:
- curl -L https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-32bit.tar.gz
  | tar -xz
- pip install Pygments
script:
- "./hugo"
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
- rsync -r ./public/* yanzay@46.101.193.210:~/www/yanzay.com/
